import kanaType from '../types/kana';

const hiragana: kanaType[] = [
  {
    id: 'h_a',
    pronunciation: 'A',
    kana: 'あ',
    type: 'basic',
    group: 'basic',
  },
  {
    id: 'h_i',
    pronunciation: 'I',
    kana: 'い',
    type: 'basic',
    group: 'basic',
  },
  {
    id: 'h_u',
    pronunciation: 'U',
    kana: 'う',
    type: 'basic',
    group: 'basic',
  },
  {
    id: 'h_e',
    pronunciation: 'E',
    kana: 'え',
    type: 'basic',
    group: 'basic',
  },
  {
    id: 'h_o',
    pronunciation: 'O',
    kana: 'お',
    type: 'basic',
    group: 'basic',
  },
  {
    id: 'h_ka',
    pronunciation: 'KA',
    kana: 'か',
    type: 'basic',
    group: 'k',
  },
  {
    id: 'h_ki',
    pronunciation: 'KI',
    kana: 'き',
    type: 'basic',
    group: 'k',
  },
  {
    id: 'h_ku',
    pronunciation: 'KU',
    kana: 'く',
    type: 'basic',
    group: 'k',
  },
  {
    id: 'h_ke',
    pronunciation: 'KE',
    kana: 'け',
    type: 'basic',
    group: 'k',
  },
  {
    id: 'h_ko',
    pronunciation: 'KO',
    kana: 'こ',
    type: 'basic',
    group: 'k',
  },
  {
    id: 'h_sa',
    pronunciation: 'SA',
    kana: 'さ',
    type: 'basic',
    group: 's',
  },
  {
    id: 'h_shi',
    pronunciation: 'SHI',
    kana: 'し',
    type: 'basic',
    group: 's',
  },
  {
    id: 'h_su',
    pronunciation: 'SU',
    kana: 'す',
    type: 'basic',
    group: 's',
  },
  {
    id: 'h_se',
    pronunciation: 'SE',
    kana: 'せ',
    type: 'basic',
    group: 's',
  },
  {
    id: 'h_so',
    pronunciation: 'SO',
    kana: 'そ',
    type: 'basic',
    group: 's',
  },
  {
    id: 'h_ta',
    pronunciation: 'TA',
    kana: 'た',
    type: 'basic',
    group: 't',
  },
  {
    id: 'h_chi',
    pronunciation: 'CHI',
    kana: 'ち',
    type: 'basic',
    group: 't',
  },
  {
    id: 'h_tsu',
    pronunciation: 'TSU',
    kana: 'つ',
    type: 'basic',
    group: 't',
  },
  {
    id: 'h_te',
    pronunciation: 'TE',
    kana: 'て',
    type: 'basic',
    group: 't',
  },
  {
    id: 'h_to',
    pronunciation: 'TO',
    kana: 'と',
    type: 'basic',
    group: 't',
  },
  {
    id: 'h_na',
    pronunciation: 'NA',
    kana: 'な',
    type: 'basic',
    group: 'n',
  },
  {
    id: 'h_ni',
    pronunciation: 'NI',
    kana: 'に',
    type: 'basic',
    group: 'n',
  },
  {
    id: 'h_nu',
    pronunciation: 'NU',
    kana: 'ぬ',
    type: 'basic',
    group: 'n',
  },
  {
    id: 'h_ne',
    pronunciation: 'NE',
    kana: 'ね',
    type: 'basic',
    group: 'n',
  },
  {
    id: 'h_no',
    pronunciation: 'NO',
    kana: 'の',
    type: 'basic',
    group: 'n',
  },
  {
    id: 'h_ha',
    pronunciation: 'HA',
    kana: 'は',
    type: 'basic',
    group: 'h',
  },
  {
    id: 'h_hi',
    pronunciation: 'HI',
    kana: 'ひ',
    type: 'basic',
    group: 'h',
  },
  {
    id: 'h_fu',
    pronunciation: 'FU',
    kana: 'ふ',
    type: 'basic',
    group: 'h',
  },
  {
    id: 'h_he',
    pronunciation: 'HE',
    kana: 'へ',
    type: 'basic',
    group: 'h',
  },
  {
    id: 'h_ho',
    pronunciation: 'HO',
    kana: 'ほ',
    type: 'basic',
    group: 'h',
  },
  {
    id: 'h_ma',
    pronunciation: 'MA',
    kana: 'ま',
    type: 'basic',
    group: 'm',
  },
  {
    id: 'h_mi',
    pronunciation: 'MI',
    kana: 'み',
    type: 'basic',
    group: 'm',
  },
  {
    id: 'h_mu',
    pronunciation: 'MU',
    kana: 'む',
    type: 'basic',
    group: 'm',
  },
  {
    id: 'h_me',
    pronunciation: 'ME',
    kana: 'め',
    type: 'basic',
    group: 'm',
  },
  {
    id: 'h_mo',
    pronunciation: 'MO',
    kana: 'も',
    type: 'basic',
    group: 'm',
  },
  {
    id: 'h_ya',
    pronunciation: 'YA',
    kana: 'や',
    type: 'basic',
    group: 'y',
  },
  {
    id: 'h_yu',
    pronunciation: 'YU',
    kana: 'ゆ',
    type: 'basic',
    group: 'y',
  },
  {
    id: 'h_yo',
    pronunciation: 'YO',
    kana: 'よ',
    type: 'basic',
    group: 'y',
  },
  {
    id: 'h_ra',
    pronunciation: 'RA',
    kana: 'ら',
    type: 'basic',
    group: 'r',
  },
  {
    id: 'h_ri',
    pronunciation: 'RI',
    kana: 'り',
    type: 'basic',
    group: 'r',
  },
  {
    id: 'h_ru',
    pronunciation: 'RU',
    kana: 'る',
    type: 'basic',
    group: 'r',
  },
  {
    id: 'h_re',
    pronunciation: 'RE',
    kana: 'れ',
    type: 'basic',
    group: 'r',
  },
  {
    id: 'h_ro',
    pronunciation: 'RO',
    kana: 'ろ',
    type: 'basic',
    group: 'r',
  },
  {
    id: 'h_wa',
    pronunciation: 'WA',
    kana: 'わ',
    type: 'basic',
    group: 'w',
  },
  {
    id: 'h_wo',
    pronunciation: '(W)O',
    kana: 'を',
    type: 'basic',
    group: 'w',
  },
  {
    id: 'h_n',
    pronunciation: 'N',
    kana: 'ん',
    type: 'basic',
    group: 'n/m',
  },
  {
    id: 'h_ga',
    pronunciation: 'GA',
    kana: 'が',
    type: 'tenten',
    group: 'k',
  },
  {
    id: 'h_gi',
    pronunciation: 'GI',
    kana: 'ぎ',
    type: 'tenten',
    group: 'g',
  },
  {
    id: 'h_gu',
    pronunciation: 'GU',
    kana: 'ぐ',
    type: 'tenten',
    group: 'g',
  },
  {
    id: 'h_ge',
    pronunciation: 'GE',
    kana: 'げ',
    type: 'tenten',
    group: 'g',
  },
  {
    id: 'h_go',
    pronunciation: 'GO',
    kana: 'ご',
    type: 'tenten',
    group: 'g',
  },
  {
    id: 'h_za',
    pronunciation: 'ZA',
    kana: 'ざ',
    type: 'tenten',
    group: 'z',
  },
  {
    id: 'h_zi',
    pronunciation: 'JI',
    kana: 'じ',
    type: 'tenten',
    group: 'z',
  },
  {
    id: 'h_zu',
    pronunciation: 'ZU',
    kana: 'ず',
    type: 'tenten',
    group: 'z',
  },
  {
    id: 'h_ze',
    pronunciation: 'ZE',
    kana: 'ぜ',
    type: 'tenten',
    group: 'z',
  },
  {
    id: 'h_zo',
    pronunciation: 'ZO',
    kana: 'ぞ',
    type: 'tenten',
    group: 'z',
  },
  {
    id: 'h_da',
    pronunciation: 'DA',
    kana: 'だ',
    type: 'tenten',
    group: 'd',
  },
  {
    id: 'h_di',
    pronunciation: 'DI',
    kana: 'ぢ',
    type: 'tenten',
    group: 'd',
  },
  {
    id: 'h_du',
    pronunciation: 'DSU',
    kana: 'づ',
    type: 'tenten',
    group: 'd',
  },
  {
    id: 'h_de',
    pronunciation: 'DE',
    kana: 'で',
    type: 'tenten',
    group: 'd',
  },
  {
    id: 'h_do',
    pronunciation: 'DO',
    kana: 'ど',
    type: 'tenten',
    group: 'd',
  },
  {
    id: 'h_ba',
    pronunciation: 'BA',
    kana: 'ば',
    type: 'tenten',
    group: 'b',
  },
  {
    id: 'h_bi',
    pronunciation: 'BI',
    kana: 'び',
    type: 'tenten',
    group: 'b',
  },
  {
    id: 'h_bu',
    pronunciation: 'BU',
    kana: 'ぶ',
    type: 'tenten',
    group: 'b',
  },
  {
    id: 'h_be',
    pronunciation: 'BE',
    kana: 'べ',
    type: 'tenten',
    group: 'b',
  },
  {
    id: 'h_bo',
    pronunciation: 'BO',
    kana: 'ぼ',
    type: 'tenten',
    group: 'b',
  },
  {
    id: 'h_pa',
    pronunciation: 'PA',
    kana: 'ぱ',
    type: 'tenten',
    group: 'p',
  },
  {
    id: 'h_pi',
    pronunciation: 'PI',
    kana: 'ぴ',
    type: 'tenten',
    group: 'p',
  },
  {
    id: 'h_pu',
    pronunciation: 'PU',
    kana: 'ぷ',
    type: 'tenten',
    group: 'p',
  },
  {
    id: 'h_pe',
    pronunciation: 'PE',
    kana: 'ぺ',
    type: 'tenten',
    group: 'p',
  },
  {
    id: 'h_po',
    pronunciation: 'PO',
    kana: 'ぽ',
    type: 'tenten',
    group: 'p',
  },
  {
    id: 'h_kya',
    pronunciation: 'KYA',
    kana: 'きゃ',
    type: 'yoon',
    group: 'ky',
  },
  {
    id: 'h_kyu',
    pronunciation: 'KYU',
    kana: 'きゅ',
    type: 'yoon',
    group: 'ky',
  },
  {
    id: 'h_kyo',
    pronunciation: 'KYO',
    kana: 'きょ',
    type: 'yoon',
    group: 'ky',
  },
  {
    id: 'h_sha',
    pronunciation: 'SHA',
    kana: 'しゃ',
    type: 'yoon',
    group: 'sh',
  },
  {
    id: 'h_shu',
    pronunciation: 'SHU',
    kana: 'しゅ',
    type: 'yoon',
    group: 'sh',
  },
  {
    id: 'h_sho',
    pronunciation: 'SHO',
    kana: 'しょ',
    type: 'yoon',
    group: 'sh',
  },
  {
    id: 'h_cha',
    pronunciation: 'CHA',
    kana: 'ちゃ',
    type: 'yoon',
    group: 'ch',
  },
  {
    id: 'h_chu',
    pronunciation: 'CHU',
    kana: 'ちゅ',
    type: 'yoon',
    group: 'ch',
  },
  {
    id: 'h_cho',
    pronunciation: 'CHO',
    kana: 'ちょ',
    type: 'yoon',
    group: 'ch',
  },
  {
    id: 'h_nya',
    pronunciation: 'NYA',
    kana: 'にゃ',
    type: 'yoon',
    group: 'ny',
  },
  {
    id: 'h_nyu',
    pronunciation: 'NYU',
    kana: 'にゅ',
    type: 'yoon',
    group: 'ny',
  },
  {
    id: 'h_nyo',
    pronunciation: 'NYO',
    kana: 'にょ',
    type: 'yoon',
    group: 'ny',
  },
  {
    id: 'h_hya',
    pronunciation: 'HYA',
    kana: 'ひゃ',
    type: 'yoon',
    group: 'hy',
  },
  {
    id: 'h_hyu',
    pronunciation: 'HYU',
    kana: 'ひゅ',
    type: 'yoon',
    group: 'hy',
  },
  {
    id: 'h_hyo',
    pronunciation: 'HYO',
    kana: 'ひょ',
    type: 'yoon',
    group: 'hy',
  },
  {
    id: 'h_mya',
    pronunciation: 'MYA',
    kana: 'みゃ',
    type: 'yoon',
    group: 'my',
  },
  {
    id: 'h_myu',
    pronunciation: 'MYU',
    kana: 'みゅ',
    type: 'yoon',
    group: 'my',
  },
  {
    id: 'h_myo',
    pronunciation: 'MYO',
    kana: 'みょ',
    type: 'yoon',
    group: 'my',
  },
  {
    id: 'h_rya',
    pronunciation: 'RYA',
    kana: 'りゃ',
    type: 'yoon',
    group: 'ry',
  },
  {
    id: 'h_ryu',
    pronunciation: 'RYU',
    kana: 'りゅ',
    type: 'yoon',
    group: 'ry',
  },
  {
    id: 'h_ryo',
    pronunciation: 'RYO',
    kana: 'りょ',
    type: 'yoon',
    group: 'ry',
  },
  {
    id: 'h_gya',
    pronunciation: 'GYA',
    kana: 'ぎゃ',
    type: 'yoon',
    group: 'gy',
  },
  {
    id: 'h_gyu',
    pronunciation: 'GYU',
    kana: 'ぎゅ',
    type: 'yoon',
    group: 'gy',
  },
  {
    id: 'h_gyo',
    pronunciation: 'GYO',
    kana: 'ぎょ',
    type: 'yoon',
    group: 'gy',
  },
  {
    id: 'h_ja',
    pronunciation: 'JA',
    kana: 'じゃ',
    type: 'yoon',
    group: 'j',
  },
  {
    id: 'h_ju',
    pronunciation: 'JU',
    kana: 'じゅ',
    type: 'yoon',
    group: 'j',
  },
  {
    id: 'h_jo',
    pronunciation: 'JO',
    kana: 'じょ',
    type: 'yoon',
    group: 'j',
  },
  {
    id: 'h_bya',
    pronunciation: 'BYA',
    kana: 'びゃ',
    type: 'yoon',
    group: 'by',
  },
  {
    id: 'h_byu',
    pronunciation: 'BYU',
    kana: 'びゅ',
    type: 'yoon',
    group: 'by',
  },
  {
    id: 'h_byo',
    pronunciation: 'BYO',
    kana: 'びょ',
    type: 'yoon',
    group: 'by',
  },
  {
    id: 'h_pya',
    pronunciation: 'PYA',
    kana: 'ぴゃ',
    type: 'yoon',
    group: 'py',
  },
  {
    id: 'h_pyu',
    pronunciation: 'PYU',
    kana: 'ぴゅ',
    type: 'yoon',
    group: 'py',
  },
  {
    id: 'h_pyo',
    pronunciation: 'PYO',
    kana: 'ぴょ',
    type: 'yoon',
    group: 'py',
  },
];

export default hiragana;
